swipe:
  3:
    begin:
      command: xdotool keydown Alt
    right:
      update:
        command: xdotool key Tab
        interval: 5
    left:
      update:
        command: xdotool key Shift+Tab
        interval: 5
    end:
      command: xdotool keyup Alt
  4: 
    left: 
      command: xdotool key ctrl+alt+Right
    right: 
      command: xdotool key ctrl+alt+Left
    up: 
      command: xdotool key ctrl+alt+Up
    down: 
      command: xdotool key ctrl+alt+Down
pinch:
  in:
    command: xdotool key ctrl+plus
  out:
    command: xdotool key ctrl+minus

threshold:
  swipe: 0.5
  pinch: 1

interval:
  swipe: 0.5
  pinch: 0.5